// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Aqe64G7fGBn6-USZv56J11feP727XQg',
    appId: '1:1097900532875:web:bb865d637f247e9da7608e',
    messagingSenderId: '1097900532875',
    projectId: 'hacathon-project-97d09',
    authDomain: 'hacathon-project-97d09.firebaseapp.com',
    storageBucket: 'hacathon-project-97d09.firebasestorage.app',
    measurementId: 'G-RX36MTL3PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmYz2IPrATWl33-3fanFzFEVCzoUeUYgY',
    appId: '1:1097900532875:android:a3f254433e504de2a7608e',
    messagingSenderId: '1097900532875',
    projectId: 'hacathon-project-97d09',
    storageBucket: 'hacathon-project-97d09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbiCLjzC5BB4SSmGh_zaDf6oAydgJNxK4',
    appId: '1:1097900532875:ios:771d4b3df13e6feea7608e',
    messagingSenderId: '1097900532875',
    projectId: 'hacathon-project-97d09',
    storageBucket: 'hacathon-project-97d09.firebasestorage.app',
    iosClientId: '1097900532875-epds9cvvule5ro79m4uk4ra8cbc42t1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbiCLjzC5BB4SSmGh_zaDf6oAydgJNxK4',
    appId: '1:1097900532875:ios:771d4b3df13e6feea7608e',
    messagingSenderId: '1097900532875',
    projectId: 'hacathon-project-97d09',
    storageBucket: 'hacathon-project-97d09.firebasestorage.app',
    iosClientId: '1097900532875-epds9cvvule5ro79m4uk4ra8cbc42t1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Aqe64G7fGBn6-USZv56J11feP727XQg',
    appId: '1:1097900532875:web:78e4a02488b9362ea7608e',
    messagingSenderId: '1097900532875',
    projectId: 'hacathon-project-97d09',
    authDomain: 'hacathon-project-97d09.firebaseapp.com',
    storageBucket: 'hacathon-project-97d09.firebasestorage.app',
    measurementId: 'G-MG1J0V2MLJ',
  );
}
